// Random quote API:
// http://api.quotable.io/random
// Author's GitHub: https://github.com/lukePeavey/quotable
//
//
// Gender API:
// gender-api.com
// Guess gender by name.
//
//
// Random face API:
// https://fakeface.rest/
// Random, AI generated faces, based on min-max age and gender.
// "This API returns image URLs of fake human faces
// generated by the website thispersondoesnotexist.com."
//
//
// Trying to fetch data from many web APIs,
// when developing locally, produces CORS errors.
// Used PROXY to get around that: https://cors-anywhere.herokuapp.com/.
// More info: https://medium.com/swlh/avoiding-cors-errors-on-localhost-in-2020-5a656ed8cefa
//
//
// All APIs work great and talk to each other nicely. The only issue is
// that PROXY has requests limit (not sure how much, but around couple hundred per hour),
// also GENDER API has limit of 500 requests a month (if it runs out and get error
// (gender=unknown), feed random face with no gender).

// JSON responses from gender, random face and quote APIs stored in arrays
let gender = [];
let randomFace = [];
let quoteContent = [];

// PROXY API
const APIproxy = 'https://cors-anywhere.herokuapp.com/';

// get and display random quote
async function displayRandomQuote() {
  try {
    const response = await fetch('https://api.quotable.io/random');
    const data = await response.json();
    quoteContent = [data];
  } catch (e) {
    quoteContent[0].content =
      'Here should be random quote, but something went wrong.';
  }
  let p = document.createElement('p');
  p.classList.add('randomQuote');
  let randomQuoteDiv = document.getElementById('randomQuote');
  randomQuoteDiv.innerHTML = '';
  p.innerText = '"' + quoteContent[0].content + '"';
  randomQuoteDiv.appendChild(p);
}

// get MP's name from DOM and request gender from it;
async function getGender() {
  // get only firstname
  const name = document.getElementById('mpName').innerText.split(' ')[0];
  const url = APIproxy + 'https://gender-api.com/get?name=' + name; // + '&key=oNrWDverHQkAtDXMDW'; // uncommment this line to get gender
  const opts = { headers: { Accept: 'application/json' } };
  try {
    const response = await fetch(url, opts);
    const data = await response.json();
    console.log(url);
    gender = [data];
  } catch (e) {
    gender = [{ gender: 'unknown' }];
  }
  return true;
}

// call gender function;
// use gender response and MP's age from DOM
// as parameters for random face API request
async function getRandomFace() {
  await getGender();
  faceGender = gender[0].gender == 'unknown' ? '' : gender[0].gender;
  const age = document.getElementById('age').innerText;
  const minAge = age > 20 ? parseInt(age) - 2 : age;
  const maxAge = parseInt(age) + 2;
  const url =
    APIproxy +
    'https://fakeface.rest/face/json?minimum_age=' +
    minAge +
    '&maximum_age=' +
    maxAge +
    '&gender=' +
    faceGender;
  const opts = { headers: { Accept: 'application/json' } };
  try {
    const response = await fetch(url, opts);
    const data = await response.json();
    randomFace = [data];
  } catch (e) {
    randomFace = [{ image_url: 'img/api_broken.jpg' }];
  }
  return true;
}

// display random face on page
async function displayRandomFace() {
  await getRandomFace();
  let img = document.createElement('img');
  img.classList.add('randomFace');
  let randomFaceDiv = document.getElementById('randomFace');
  img.setAttribute('src', randomFace[0].image_url);
  randomFaceDiv.innerHTML = '';
  randomFaceDiv.appendChild(img);
}

displayRandomQuote();
displayRandomFace();
