// Gender API from:
// gender-api.com
// Guess gender by name and pass it to
// random face generator.
//
//
// Random face API from:
// https://fakeface.rest/
// Random, AI generated faces, based on min-max age and gender.
// "This API returns image URLs of fake human faces
// generated by the website thispersondoesnotexist.com."
//
//
// Trying to fetch data from any web API,
// when developing locally, produces CORS errors.
// Used PROXY to get around that: https://cors-anywhere.herokuapp.com/.
// More info: https://medium.com/swlh/avoiding-cors-errors-on-localhost-in-2020-5a656ed8cefa

// JSON responses from gender and random face API stored in arrays
let gender = [];
let randomFace = [];

// get MP's name from DOM and request gender from it;
// push result to gender[];
async function getGender() {
  const name = document.getElementById('mpName').innerText.split(' ')[0]; // get only firstname
  const APIproxy = 'https://cors-anywhere.herokuapp.com/';
  const url =
    APIproxy +
    'https://gender-api.com/get?name=' +
    name +
    '&key=oNrWDverHQkAtDXMDW<ekstraklucz>'; // PAMIETAC O KLUCZU PRZED ODDANIEM
  const opts = { headers: { Accept: 'application/json' } };
  const response = await fetch(url, opts);
  const data = await response.json();
  gender.push(data);
  return true;
}

// call gender function;
// use gender response and MP's age from DOM
// as parameters for random face API request
async function getRandomFace() {
  await getGender();
  let faceGender = gender[0].gender !== 'unknown' ? gender[0].gender : '';
  const age = document.getElementById('age').innerText;
  const minAge = age > 20 ? parseInt(age) - 2 : age;
  const maxAge = parseInt(age) + 2;
  const APIproxy = 'https://cors-anywhere.herokuapp.com/';
  const url =
    APIproxy +
    'https://fakeface.rest/face/json?minimum_age=' +
    minAge +
    '&maximum_age=' +
    maxAge +
    '&gender=' +
    faceGender;
  // console.log(faceGender);
  // console.log(url);
  const opts = { headers: { Accept: 'application/json' } };
  const response = await fetch(url, opts);
  const data = await response.json();
  randomFace.push(data);
  return true;
}

// get random face and display on page
async function displayRandomFace() {
  await getRandomFace();
  let img = document.createElement('img');
  img.classList.add('randomFace');
  let randomFaceDiv = document.getElementById('randomFace');
  img.setAttribute('src', randomFace[0].image_url);
  randomFaceDiv.appendChild(img);
}

displayRandomFace();
console.log('displayRandomFace();');
